import type { Metadata } from "next";
import { Source_Serif_4 } from "next/font/google";
import "../globals.css";
import { AuthProvider } from "@/context/AuthContext";
import NextTopLoader from "nextjs-toploader";

const sourceSerif = Source_Serif_4({
  variable: "--font-source-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2978396974503639"
          crossOrigin="anonymous"
        ></script>
      </head>
      <body
        className={`${sourceSerif.variable} antialiased max-w-[1660px] w-full mx-auto `}
      >
        <NextTopLoader color="#FFFFFF" height={3} showSpinner={false} />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}